/// Flutter icons HNReaderIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HNReaderIcon
///      fonts:
///       - asset: fonts/HNReaderIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class HNReaderIcon {
  HNReaderIcon._();

  static const _kFontFam = 'HNReaderIcon';

  static const IconData github_circled = const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData stackoverflow = const IconData(0xf16c, fontFamily: _kFontFam);
}
